Add files via upload

diff --git a/.github/workflows/build-patch-zlib-ng-musl-gcc-g++.yml b/.github/workflows/build-patch-zlib-ng-musl-gcc-g++.yml
--- a/.github/workflows/build-patch-zlib-ng-musl-gcc-g++.yml
+++ b/.github/workflows/build-patch-zlib-ng-musl-gcc-g++.yml
@@ -317,7 +317,7 @@ jobs:
           rm -rf objs/
 
           # 2. 核心调整：--with-cc 直接赋予绝对路径，彻底粉碎 Nginx 子 Shell 的找不到编译器魔咒
-          CC="/opt/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" ./auto/configure \
+          ./auto/configure \
             --with-cc="/opt/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc" \
             --prefix=/etc/nginx \
             --sbin-path=/usr/sbin/nginx \
@@ -361,8 +361,8 @@ jobs:
             --with-pcre \
             --with-pcre-jit \
             --build="Commit ID: $(git rev-parse --short HEAD). Openssl_Commit_ID: ${{ env.Openssl_Commit_ID }}. Rosebe Add patch: Dynamic TLS Record support. Add with-zlib: zlib-ng. Compiler musl-gcc. And build on $(date +%Y_%m_%d-%H:%M:%S)" \
-            --with-cc-opt="-O2 -static -I${BROTLI_DIR}/include -I${ZLIB_NG_DIR} -I${PCRE2_DIR}/include -I${OPENSSL_DIR}/include" \
-            --with-ld-opt="-O2 -static \
+            --with-cc-opt="-O2 -I${BROTLI_DIR}/include -I${ZLIB_NG_DIR} -I${PCRE2_DIR}/include -I${OPENSSL_DIR}/include" \
+            --with-ld-opt="-static \
               ${BROTLI_DIR}/lib/libbrotlienc.a \
               ${BROTLI_DIR}/lib/libbrotlicommon.a \
               ${BROTLI_DIR}/lib/libbrotlidec.a \
@@ -375,6 +375,12 @@ jobs:
           #--with-zlib-opt='--static' \
           #--with-cc-opt='-static -static-libgcc -march=x86-64 -O2'
 
+          # 3. 如果配置失败，由于底层已经可以进入配置流，若遇到问题将可以直接查看真正的 autoconf.err 原因
+          if [ ! -f "objs/Makefile" ]; then
+              echo "==== CONFIGURATION FAILED! SHOWING ERROR LOG ===="
+              cat objs/autoconf.err 2>/dev/null || true
+              exit 1
+          fi
           #make -j$(nproc --all)
           make -j$(nproc --all) || (cat objs/autoconf.err && exit 1)
           #make || (cat objs/autoconf.err && exit 1)
